"""updating image table

Revision ID: 359c9457d7f1
Revises: ac0bb245afa0
Create Date: 2025-05-01 16:18:48.118172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '359c9457d7f1'
down_revision: Union[str, None] = 'ac0bb245afa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_sources', sa.Column('page', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_sources', 'page')
    # ### end Alembic commands ###
