"""creating tables

Revision ID: 6208539e9aeb
Revises: 
Create Date: 2025-07-22 00:16:39.828587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6208539e9aeb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('username', 'email'),
    schema='frontend_data'
    )
    op.create_index(op.f('ix_frontend_data_user_info_id'), 'user_info', ['id'], unique=False, schema='frontend_data')
    op.create_table('part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upper_count', sa.Integer(), nullable=False),
    sa.Column('lower_count', sa.Integer(), nullable=False),
    sa.CheckConstraint('id IN ( 1, 2, 3)', name='check_valid_bp_id'),
    sa.PrimaryKeyConstraint('id'),
    schema='training_sources'
    )
    op.create_table('body_part_counts',
    sa.Column('id', sa.Enum('n', 'f', 'h', 'a', 'l', 's', 'c', 'b', 'e', name='body_id_enum'), nullable=False),
    sa.Column('counts', sa.Integer(), nullable=False),
    sa.Column('where', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['where'], ['training_sources.part.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='training_sources'
    )
    op.create_table('research_paper_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_name', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('where', sa.String(), nullable=False),
    sa.Column('part_id', sa.Enum('n', 'f', 'h', 'a', 'l', 's', 'c', 'b', 'e', name='body_id_enum'), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['training_sources.body_part_counts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_name', name='uq_textbook'),
    schema='training_sources'
    )
    op.create_index(op.f('ix_training_sources_research_paper_sources_id'), 'research_paper_sources', ['id'], unique=True, schema='training_sources')
    op.create_table('textbook_sources',
    sa.Column('textbook_id', sa.Integer(), nullable=False),
    sa.Column('textbook_name', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('where', sa.String(), nullable=False),
    sa.Column('part_id', sa.Enum('n', 'f', 'h', 'a', 'l', 's', 'c', 'b', 'e', name='body_id_enum'), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['training_sources.body_part_counts.id'], ),
    sa.PrimaryKeyConstraint('textbook_id'),
    sa.UniqueConstraint('textbook_name', 'author', name='uq_textbook_author'),
    schema='training_sources'
    )
    op.create_index(op.f('ix_training_sources_textbook_sources_textbook_id'), 'textbook_sources', ['textbook_id'], unique=True, schema='training_sources')
    op.create_table('image_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('textbook_id', sa.Integer(), nullable=True),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('has_context', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['training_sources.research_paper_sources.id'], ),
    sa.ForeignKeyConstraint(['textbook_id'], ['training_sources.textbook_sources.textbook_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='training_sources'
    )
    op.create_index(op.f('ix_training_sources_image_sources_id'), 'image_sources', ['id'], unique=True, schema='training_sources')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_sources_image_sources_id'), table_name='image_sources', schema='training_sources')
    op.drop_table('image_sources', schema='training_sources')
    op.drop_index(op.f('ix_training_sources_textbook_sources_textbook_id'), table_name='textbook_sources', schema='training_sources')
    op.drop_table('textbook_sources', schema='training_sources')
    op.drop_index(op.f('ix_training_sources_research_paper_sources_id'), table_name='research_paper_sources', schema='training_sources')
    op.drop_table('research_paper_sources', schema='training_sources')
    op.drop_table('body_part_counts', schema='training_sources')
    op.drop_table('part', schema='training_sources')
    op.drop_index(op.f('ix_frontend_data_user_info_id'), table_name='user_info', schema='frontend_data')
    op.drop_table('user_info', schema='frontend_data')
    # ### end Alembic commands ###
