"""constraints updates for textbook, research

Revision ID: ac0bb245afa0
Revises: cd44f6065868
Create Date: 2025-04-24 19:14:32.068287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac0bb245afa0'
down_revision: Union[str, None] = 'cd44f6065868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_textbook', 'research_paper_sources', ['paper_name'])
    op.create_unique_constraint('uq_textbook_author', 'textbook_sources', ['textbook_name', 'author'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_textbook_author', 'textbook_sources', type_='unique')
    op.drop_constraint('uq_textbook', 'research_paper_sources', type_='unique')
    # ### end Alembic commands ###
