"""recreating tables and stuff

Revision ID: cc575f84500d
Revises: 4300edc8d58e
Create Date: 2025-07-28 01:12:53.529411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc575f84500d'
down_revision: Union[str, None] = '4300edc8d58e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='frontend_data'
    )
    op.create_index(op.f('ix_frontend_data_users_email'), 'users', ['email'], unique=True, schema='frontend_data')
    op.create_index(op.f('ix_frontend_data_users_username'), 'users', ['username'], unique=True, schema='frontend_data')
    op.create_table('login_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('login_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['frontend_data.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='frontend_data'
    )
    op.create_index(op.f('ix_frontend_data_login_history_user_id'), 'login_history', ['user_id'], unique=False, schema='frontend_data')
    op.create_table('body_part_counts',
    sa.Column('id', sa.Enum('n', 'f', 'h', 'a', 'l', 's', 'c', 'b', 'e', name='body_id_enum'), nullable=False),
    sa.Column('counts', sa.Integer(), nullable=False),
    sa.Column('source_part_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_part_id'], ['training_sources.part.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='training_sources'
    )
    op.create_table('problem_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('body_part_id', sa.Enum('n', 'f', 'h', 'a', 'l', 's', 'c', 'b', 'e', name='body_id_enum'), nullable=False),
    sa.Column('had_this_problem_before', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('previous_problem_date', sa.DateTime(), nullable=True),
    sa.Column('what_helped_before', sa.Text(), nullable=True),
    sa.Column('had_physical_therapy_before', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('previous_unrelated_problem', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['body_part_id'], ['training_sources.body_part_counts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['frontend_data.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='frontend_data'
    )
 


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_sources_image_sources_id'), table_name='image_sources', schema='training_sources')
    #op.drop_table('image_sources', schema='training_sources')
   # op.drop_index(op.f('ix_training_sources_textbook_sources_textbook_id'), table_name='textbook_sources', schema='training_sources')
   # op.drop_table('textbook_sources', schema='training_sources')
   # op.drop_index(op.f('ix_training_sources_research_paper_sources_id'), table_name='research_paper_sources', schema='training_sources')
    #op.drop_table('research_paper_sources', schema='training_sources')
    op.drop_index(op.f('ix_frontend_data_problem_reports_user_id'), table_name='problem_reports', schema='frontend_data')
    op.drop_table('problem_reports', schema='frontend_data')
    op.drop_table('body_part_counts', schema='training_sources')
    op.drop_index(op.f('ix_frontend_data_login_history_user_id'), table_name='login_history', schema='frontend_data')
    op.drop_table('login_history', schema='frontend_data')
    
    op.drop_index(op.f('ix_frontend_data_users_username'), table_name='users', schema='frontend_data')
    op.drop_index(op.f('ix_frontend_data_users_email'), table_name='users', schema='frontend_data')
    op.drop_table('users', schema='frontend_data')
    # ### end Alembic commands ###
