"""initial schema

Revision ID: cd44f6065868
Revises: 
Create Date: 2025-04-23 20:04:31.461610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd44f6065868'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('body_part_counts', 'counts',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('body_part_counts', 'where',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('image_sources', 'date_added',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('image_sources', 'size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('image_sources', 'file_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('part', 'upper_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('part', 'lower_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('research_paper_sources', 'paper_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('research_paper_sources', 'size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('research_paper_sources', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('research_paper_sources', 'where',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('research_paper_sources', 'part_id',
               existing_type=postgresql.ENUM('n', 'f', 'h', 'a', 'l', 's', 'c', 'b', 'e', name='body_id_enum'),
               nullable=False)
    op.alter_column('textbook_sources', 'textbook_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('textbook_sources', 'author',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('textbook_sources', 'size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('textbook_sources', 'date_added',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('textbook_sources', 'where',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('textbook_sources', 'part_id',
               existing_type=postgresql.ENUM('n', 'f', 'h', 'a', 'l', 's', 'c', 'b', 'e', name='body_id_enum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('textbook_sources', 'part_id',
               existing_type=postgresql.ENUM('n', 'f', 'h', 'a', 'l', 's', 'c', 'b', 'e', name='body_id_enum'),
               nullable=True)
    op.alter_column('textbook_sources', 'where',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('textbook_sources', 'date_added',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('textbook_sources', 'size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('textbook_sources', 'author',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('textbook_sources', 'textbook_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('research_paper_sources', 'part_id',
               existing_type=postgresql.ENUM('n', 'f', 'h', 'a', 'l', 's', 'c', 'b', 'e', name='body_id_enum'),
               nullable=True)
    op.alter_column('research_paper_sources', 'where',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('research_paper_sources', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('research_paper_sources', 'size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('research_paper_sources', 'paper_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('part', 'lower_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('part', 'upper_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('image_sources', 'file_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('image_sources', 'size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('image_sources', 'date_added',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('body_part_counts', 'where',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('body_part_counts', 'counts',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
